config/routes.rb
Rails.application.routes.draw do
  get "/home/about"=>"homes#about" ,as: "about"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to:'homes#top'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  
  attachment :profile_image
  
  validates :name,uniqueness: true
  validates :name,length: {in:2..20}
  validates :introduction,length: {maximum: 50}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     root_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user=User.find_by(id: params[:id])
    if @user.id!=current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user=User.find_by(id: params[:id])
    @book=@user.books.new
  end
  
  def index
    @book=Book.new
    @user=User.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
    <div class="col-md-3">
      <h2>User info</h2>

      <%= attachment_image_tag user, :profile_image , :fill,60,60,fallback:"no_image.jpg" %>

      <table class="table table-hover table-inverse"
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>

      <%= link_to edit_user_path(user.id) ,class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>


      <h2>New book</h2>

      <%= form_with model:@book,local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>

        <h4>Opinion</h4>
        <%= f.text_area :body %>

        <%= f.submit 'Create Book',class:"btn btn-success",style:"margin:5px 0"%>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>User info</h1>
        <% if @user.errors.any? %>
          <h2 style="color:red"><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul style="color:red">
          <% @user.errors.full_messages.each do |message| %>
            <li style="color:red"><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      <%= form_with model: @user,local:true do |f| %>
        <h3>Name</h3>
        <%= f.text_field :name %>
        
        <h3>Image</h3>
        <%= f.attachment_field :profile_image %>
        
        <h3>Introduction</h3>
        <%= f.text_area :introduction %><br/>
        
        <%= f.submit 'Update User' ,class:"btn btn-secondary" %>
        
      <% end %>
    </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list',user:current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h1>
      <table class="table table-hover table-inverse">
        <tr>
          <th>image</th>
          <th>name</th>
          <th> </th>
        </tr>
          <% @user.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image , :fill,40,40,fallback:"no_image.jpg", size:'40x40' %></td>
                <% end %>
          
              <td><%= user.name %></td>
          
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div style="padding-left:20%">
  <% if @book.errors.any? %>
    <h2 style="color:red"><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul style="color:red">
    <% @book.errors.full_messages.each do |message| %>
      <li style="color:red"><%= message %></li>
    <% end %>
    
  <% end %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list',user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h1>
      <table class="table table-hover table-inverse">
        <tr>
          <th> </th>
          <th>Title</th>
          <th>Opinion</th>
          <th>コメント数</th>
        </tr>
      <% (@user.books).each do |book| %>
        <% if book.id!=nil %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do%>
              <%= attachment_image_tag @user, :profile_image , :fill,40,40,fallback:"no_image.jpg",size:"40x40" %></td>
              <% end %>

            <td><%= link_to book.title,book_path(book.id) %></td>

            <td><%= book.body %></td>
            
            <td><%= book.book_comments.count %></td>
            <td>
                <% if book.favorites_by?(current_user,book) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fas fa-heart" style="color:red"></i>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fas fa-heart"></i>
                      <%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
                </td>
          </tr>
        <% end %>
      <% end %>
      </table>
    </div>
  </div>
</div>