config/routes.rb
Rails.application.routes.draw do
  get "/home/about"=>"homes#about" ,as: "about"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to:'homes#top'
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  validates :title,presence: true
  validates :body,presence: true
  validates :body,length: {maximum: 200}
  
  def favorites_by?(user,book)
    favorites.where(user_id: user.id,book_id: book.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def create
       @book=current_user.books.new(book_params)
       @book.user_id=current_user.id
        if @book.save
            flash[:notice]="You have created book successfully."
            redirect_to book_path(@book.id)
        else
            @books=Book.all
            render "books/index"
        end
    end

    def edit
        @book=Book.find_by(id: params[:id])
        if @book.user.id==current_user.id
            nil
        else
            redirect_to books_path
        end
    end

    def update
        @book=Book.find_by(id: params[:id])
        if @book.update(book_params)
            flash[:notice]="You have updated book successfully."
            redirect_to book_path(@book.id)
        else
            render :edit
        end

    end

    def destroy
        @book=Book.find_by(id:params[:id])
        @book.destroy
        redirect_to books_path
    end

    def show
        @book=Book.new
        @book_id=Book.find_by(id: params[:id])
        @user=@book_id.user
        @book_comment=BookComment.new
    end

    def index
        @book=Book.new
        @books=Book.all
    end

    private

    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div >
        <% if @book.errors.any? %>
          <h2 style="color:red"><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul style="color:red">
          <% @book.errors.full_messages.each do |message| %>
            <li style="color:red"><%= message %></li>
          <% end %>
          </ul
        <% end %>
      </div>
      <%= form_with model: @book,local:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>


        <p>Opinion</p>
        <%= f.text_area :body %><br/>

        <%= f.submit 'Update Book' ,class:"btn btn-success" ,style:"margin:20px 0;" %>

      <% end %>

      <p><%= link_to "Show",book_path(@book.id)  %> | <%= link_to "Back",books_path %></p>
    </div>
  </div>

</div>

app/views/books/index.html.erb
<div style="padding-left:20%">
  <% if @book.errors.any? %>
    <h2 style="color:red"><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul style="color:red">
    <% @book.errors.full_messages.each do |message| %>
      <li style="color:red"><%= message %></li>
    <% end %>

  <% end %>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list',user:current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h1>
      <table class="table table-hover table-inverse">
        <tr>
          <th> </th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image , :fill,40,40,fallback:"no_image.jpg" ,size:"40x40" %></td>
              <% end %>

            <td><%= link_to book.title,book_path(book.id) %></td>

            <td><%= book.body %></td>

            <td>
            <% if book.favorites_by?(current_user,book) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart" style="color:red"></i>
                  <%= book.favorites.count %>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              </p>
            <% end %>
            </td>
            <td>
              <p>コメント数:<%= book.book_comments.count %></p>
            </td>
          </tr>

        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list',user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h1>
      <table class="table">
            <tr>
              <td>
                <%= link_to user_path(@book_id.user.id) do %>
                <%= attachment_image_tag @book_id.user, :profile_image , :fill,40,40,fallback:"no_image.jpg", size:'40x40' %><br/><%= @book_id.user.name %></td>
                <% end %>

              <td><%= link_to @book_id.title,book_path(@book_id.id) %></td>

              <td><%= @book_id.body %></td>
               <td>
                <% if @book_id.favorites_by?(current_user,@book_id) %>
                  <p>
                    <%= link_to book_favorites_path(@book_id), method: :delete do %>
                      <i class="fas fa-heart" style="color:red"></i>
                      <%= @book_id.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book_id), method: :post do %>
                      <i class="fas fa-heart"></i>
                      <%= @book_id.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
                </td>
                <td>
                  コメント数<%= @book_id.book_comments.count %>
                </td>
              <% if @book_id.user.id==current_user.id %>
                <td><%= link_to "Edit",edit_book_path(@book_id.id),class: 'btn btn-success' %></td>

                <td><%= link_to "Destroy",book_path(@book_id.id),class: "btn btn-danger",method: :delete , data: {confirm: "本当に消しますか" } %></td>
              <% end %>
            </tr>

      </table>
      <% @book_id.book_comments.each do |book_comment| %>
        <div style="margin:5px 0">
          <%= link_to user_path(book_comment.user.id) do %>
            <%= attachment_image_tag book_comment.user, :profile_image , :fill,40,40,fallback:"no_image.jpg" ,size:"40x40" %></td>
          <% end %>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
          <% if book_comment.user.id==current_user.id %>
            <%= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment),class: "btn btn-danger",method: :delete , data: {confirm: "本当に消しますか" } %>
          <% end %>
        </div>
      <% end %>
      <div>
        <%= form_with(model:[@book_id, @book_comment], local: true) do |f| %>

          <%= f.text_area :comment %>

          <%= f.submit '送信',class:"btn btn-success",style:"margin:5px 0"%>
        <% end %>
      </div>
    </div>
  </div>
</div>